# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Elevator_Project_GUI2.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

import pygame
import os
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from ElevatorSystem import ElevatorSystem

class ElevatorGUI(object):
    def setupUi(self, ProgramForm):
        self.user = "passenger"
        self.system = ElevatorSystem()
        ProgramForm.setObjectName("ProgramForm")
        ProgramForm.resize(1200, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProgramForm.sizePolicy().hasHeightForWidth())
        ProgramForm.setSizePolicy(sizePolicy)
        ProgramForm.setMinimumSize(QtCore.QSize(1200, 900))
        ProgramForm.setMaximumSize(QtCore.QSize(1200, 900))
        ProgramForm.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/down.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProgramForm.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ProgramForm)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_24 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_18.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_18.addWidget(self.label_25, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.Button_Down_Floor_5 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Down_Floor_5.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Down_Floor_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ####
        self.Button_Down_Floor_5.setIcon(icon1)
        self.Button_Down_Floor_5.setAutoRepeat(False)
        self.Button_Down_Floor_5.setAutoRepeatInterval(100)
        self.Button_Down_Floor_5.setAutoDefault(False)
        self.Button_Down_Floor_5.setDefault(False)
        self.Button_Down_Floor_5.setFlat(False)
        self.Button_Down_Floor_5.setObjectName("Button_Down_Floor_5")
        self.gridLayout_13.addWidget(self.Button_Down_Floor_5, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 0, 3, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_20 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.Display_Floor5 = QtWidgets.QLineEdit(ProgramForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Display_Floor5.setFont(font)
        self.Display_Floor5.setObjectName("Display_Floor5")
        self.verticalLayout_6.addWidget(self.Display_Floor5)
        self.gridLayout_13.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.Button_Key_Floor5 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Key_Floor5.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Key_Floor5.setFont(font)
        self.Button_Key_Floor5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 137, 0, 255), stop:1 rgba(255, 251, 106, 255));")
        self.Button_Key_Floor5.setObjectName("Button_Key_Floor5")
        self.gridLayout_13.addWidget(self.Button_Key_Floor5, 0, 5, 1, 1)
        self.Button_Sys_Onoff_Floor_5 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Sys_Onoff_Floor_5.setEnabled(False)
        self.Button_Sys_Onoff_Floor_5.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Button_Sys_Onoff_Floor_5.setFont(font)
        self.Button_Sys_Onoff_Floor_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 40, 0, 255), stop:1 rgba(255, 106, 106, 255))")
        self.Button_Sys_Onoff_Floor_5.setObjectName("Button_Sys_Onoff_Floor_5")
        self.gridLayout_13.addWidget(self.Button_Sys_Onoff_Floor_5, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 0, 6, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem2, 0, 0, 1, 1)
        self.Button_Up_Floor_3 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Up_Floor_3.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Up_Floor_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Up_Floor_3.setIcon(icon2)
        self.Button_Up_Floor_3.setObjectName("Button_Up_Floor_3")
        self.gridLayout_15.addWidget(self.Button_Up_Floor_3, 0, 3, 1, 1)
        self.Button_Down_Floor_3 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Down_Floor_3.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Down_Floor_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_Down_Floor_3.setIcon(icon1)
        self.Button_Down_Floor_3.setObjectName("Button_Down_Floor_3")
        self.gridLayout_15.addWidget(self.Button_Down_Floor_3, 0, 2, 1, 1)
        self.Button_Sys_Onoff_Floor_3 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Sys_Onoff_Floor_3.setEnabled(False)
        self.Button_Sys_Onoff_Floor_3.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Sys_Onoff_Floor_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 40, 0, 255), stop:1 rgba(255, 106, 106, 255))")
        self.Button_Sys_Onoff_Floor_3.setObjectName("Button_Sys_Onoff_Floor_3")
        self.gridLayout_15.addWidget(self.Button_Sys_Onoff_Floor_3, 0, 4, 1, 1)
        self.Button_Key_Floor3 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Key_Floor3.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Key_Floor3.setFont(font)
        self.Button_Key_Floor3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 137, 0, 255), stop:1 rgba(255, 251, 106, 255));")
        self.Button_Key_Floor3.setObjectName("Button_Key_Floor3")
        self.gridLayout_15.addWidget(self.Button_Key_Floor3, 0, 5, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_18 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.Display_Floor3 = QtWidgets.QLineEdit(ProgramForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Display_Floor3.setFont(font)
        self.Display_Floor3.setObjectName("Display_Floor3")
        self.verticalLayout_2.addWidget(self.Display_Floor3)
        self.gridLayout_15.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 6, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_15, 8, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem3, 0, 0, 1, 1)
        self.Button_Up_Floor_2 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Up_Floor_2.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Up_Floor_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_Up_Floor_2.setIcon(icon2)
        self.Button_Up_Floor_2.setObjectName("Button_Up_Floor_2")
        self.gridLayout_16.addWidget(self.Button_Up_Floor_2, 0, 3, 1, 1)
        self.Button_Key_Floor2 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Key_Floor2.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Key_Floor2.setFont(font)
        self.Button_Key_Floor2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 137, 0, 255), stop:1 rgba(255, 251, 106, 255));")
        self.Button_Key_Floor2.setObjectName("Button_Key_Floor2")
        self.gridLayout_16.addWidget(self.Button_Key_Floor2, 0, 5, 1, 1)
        self.Button_Sys_Onoff_Floor_2 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Sys_Onoff_Floor_2.setEnabled(False)
        self.Button_Sys_Onoff_Floor_2.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Sys_Onoff_Floor_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 40, 0, 255), stop:1 rgba(255, 106, 106, 255))")
        self.Button_Sys_Onoff_Floor_2.setObjectName("Button_Sys_Onoff_Floor_2")
        self.gridLayout_16.addWidget(self.Button_Sys_Onoff_Floor_2, 0, 4, 1, 1)
        self.Button_Down_Floor_2 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Down_Floor_2.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Down_Floor_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_Down_Floor_2.setIcon(icon1)
        self.Button_Down_Floor_2.setObjectName("Button_Down_Floor_2")
        self.gridLayout_16.addWidget(self.Button_Down_Floor_2, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_21 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.Display_Floor2 = QtWidgets.QLineEdit(ProgramForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Display_Floor2.setFont(font)
        self.Display_Floor2.setObjectName("Display_Floor2")
        self.verticalLayout_7.addWidget(self.Display_Floor2)
        self.gridLayout_16.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 0, 6, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_16, 11, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 1, 0, 1, 1)
        self.Button_Down_Floor_4 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Down_Floor_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Down_Floor_4.sizePolicy().hasHeightForWidth())
        self.Button_Down_Floor_4.setSizePolicy(sizePolicy)
        self.Button_Down_Floor_4.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Down_Floor_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_Down_Floor_4.setIcon(icon1)
        self.Button_Down_Floor_4.setObjectName("Button_Down_Floor_4")
        self.gridLayout_14.addWidget(self.Button_Down_Floor_4, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.Display_Floor4 = QtWidgets.QLineEdit(ProgramForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Display_Floor4.setFont(font)
        self.Display_Floor4.setObjectName("Display_Floor4")
        self.verticalLayout_5.addWidget(self.Display_Floor4)
        self.gridLayout_14.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.Button_Up_Floor_4 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Up_Floor_4.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Up_Floor_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_Up_Floor_4.setIcon(icon2)
        self.Button_Up_Floor_4.setObjectName("Button_Up_Floor_4")
        self.gridLayout_14.addWidget(self.Button_Up_Floor_4, 1, 3, 1, 1)
        self.Button_Key_Floor4 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Key_Floor4.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Key_Floor4.setFont(font)
        self.Button_Key_Floor4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 137, 0, 255), stop:1 rgba(255, 251, 106, 255));")
        self.Button_Key_Floor4.setObjectName("Button_Key_Floor4")
        self.gridLayout_14.addWidget(self.Button_Key_Floor4, 1, 5, 1, 1)
        self.Button_Sys_Onoff_Floor_4 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Sys_Onoff_Floor_4.setEnabled(False)
        self.Button_Sys_Onoff_Floor_4.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Sys_Onoff_Floor_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 40, 0, 255), stop:1 rgba(255, 106, 106, 255))")
        self.Button_Sys_Onoff_Floor_4.setObjectName("Button_Sys_Onoff_Floor_4")
        self.gridLayout_14.addWidget(self.Button_Sys_Onoff_Floor_4, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_14.addWidget(self.label_2, 1, 6, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_14, 5, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_5.addLayout(self.gridLayout_19, 16, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem5, 0, 0, 1, 1)
        self.Button_Sys_Onoff_Floor_1 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Sys_Onoff_Floor_1.setEnabled(False)
        self.Button_Sys_Onoff_Floor_1.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Sys_Onoff_Floor_1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 40, 0, 255), stop:1 rgba(255, 106, 106, 255))")
        self.Button_Sys_Onoff_Floor_1.setObjectName("Button_Sys_Onoff_Floor_1")
        self.gridLayout_17.addWidget(self.Button_Sys_Onoff_Floor_1, 0, 4, 1, 1)
        self.Button_Up_Floor_1 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Up_Floor_1.setMinimumSize(QtCore.QSize(0, 42))
        self.Button_Up_Floor_1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_Up_Floor_1.setIcon(icon2)
        self.Button_Up_Floor_1.setObjectName("Button_Up_Floor_1")
        self.gridLayout_17.addWidget(self.Button_Up_Floor_1, 0, 3, 1, 1)
        self.Button_Key_Floor1 = QtWidgets.QPushButton(ProgramForm)
        self.Button_Key_Floor1.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Key_Floor1.setFont(font)
        self.Button_Key_Floor1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 137, 0, 255), stop:1 rgba(255, 251, 106, 255));")
        self.Button_Key_Floor1.setObjectName("Button_Key_Floor1")
        self.gridLayout_17.addWidget(self.Button_Key_Floor1, 0, 5, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.Display_Floor1 = QtWidgets.QLineEdit(ProgramForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Display_Floor1.setFont(font)
        self.Display_Floor1.setObjectName("Display_Floor1")
        self.verticalLayout_8.addWidget(self.Display_Floor1)
        self.gridLayout_17.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_17.addWidget(self.label_5, 0, 6, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_17, 14, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(ProgramForm)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_5.addWidget(self.line_8, 15, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(ProgramForm)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 3, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(ProgramForm)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 12, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(ProgramForm)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 6, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(ProgramForm)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_5.addWidget(self.line_6, 9, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem7, 10, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem8, 13, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem9, 7, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem10, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.Diplay_Inside = QtWidgets.QLCDNumber(ProgramForm)
        self.Diplay_Inside.setMinimumSize(QtCore.QSize(201, 50))
        self.Diplay_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(203, 203, 203, 255), stop:1 rgba(217, 217, 217, 255));\n"
"color: rgb(255, 0, 0);")
        self.Diplay_Inside.setSmallDecimalPoint(True)
        self.Diplay_Inside.setDigitCount(1)
        self.Diplay_Inside.setMode(QtWidgets.QLCDNumber.Dec)
        self.Diplay_Inside.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Diplay_Inside.setProperty("intValue", 1)
        self.Diplay_Inside.setObjectName("Diplay_Inside")
        self.gridLayout_12.addWidget(self.Diplay_Inside, 4, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem11, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_23 = QtWidgets.QLabel(ProgramForm)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("Resources/bell-7.png"))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.lineEdit_6 = QtWidgets.QLineEdit(ProgramForm)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Button_Close_Door_Inside = QtWidgets.QToolButton(ProgramForm)
        self.Button_Close_Door_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Close_Door_Inside.setFont(font)
        self.Button_Close_Door_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Close_Door_Inside.setIcon(icon3)
        self.Button_Close_Door_Inside.setIconSize(QtCore.QSize(40, 40))
        self.Button_Close_Door_Inside.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Button_Close_Door_Inside.setObjectName("Button_Close_Door_Inside")
        self.gridLayout_10.addWidget(self.Button_Close_Door_Inside, 5, 0, 1, 1)
        self.Button_Stop_Inside = QtWidgets.QToolButton(ProgramForm)
        self.Button_Stop_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Stop_Inside.setFont(font)
        self.Button_Stop_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/Icons-Land-Play-Stop-Pause-Stop-Normal-Red.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Stop_Inside.setIcon(icon4)
        self.Button_Stop_Inside.setIconSize(QtCore.QSize(40, 40))
        self.Button_Stop_Inside.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Button_Stop_Inside.setObjectName("Button_Stop_Inside")
        self.gridLayout_10.addWidget(self.Button_Stop_Inside, 6, 0, 1, 1)
        self.Button_2_Inside = QtWidgets.QPushButton(ProgramForm)
        self.Button_2_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_2_Inside.setFont(font)
        self.Button_2_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_2_Inside.setObjectName("Button_2_Inside")
        self.gridLayout_10.addWidget(self.Button_2_Inside, 1, 1, 1, 1)
        self.Button_Sys_Onoff_Inside = QtWidgets.QToolButton(ProgramForm)
        self.Button_Sys_Onoff_Inside.setEnabled(False)
        self.Button_Sys_Onoff_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Sys_Onoff_Inside.setFont(font)
        self.Button_Sys_Onoff_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 40, 0, 255), stop:1 rgba(255, 106, 106, 255))")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Resources/power-off-icon-hi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Sys_Onoff_Inside.setIcon(icon5)
        self.Button_Sys_Onoff_Inside.setIconSize(QtCore.QSize(40, 40))
        self.Button_Sys_Onoff_Inside.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Button_Sys_Onoff_Inside.setObjectName("Button_Sys_Onoff_Inside")
        self.gridLayout_10.addWidget(self.Button_Sys_Onoff_Inside, 4, 0, 1, 1)
        self.Button_Key_Inside = QtWidgets.QToolButton(ProgramForm)
        self.Button_Key_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Key_Inside.setFont(font)
        self.Button_Key_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 137, 0, 255), stop:1 rgba(255, 251, 106, 255));")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Resources/man key.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Key_Inside.setIcon(icon6)
        self.Button_Key_Inside.setIconSize(QtCore.QSize(40, 40))
        self.Button_Key_Inside.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Button_Key_Inside.setObjectName("Button_Key_Inside")
        self.gridLayout_10.addWidget(self.Button_Key_Inside, 4, 1, 1, 1)
        self.Button_4_Inside = QtWidgets.QPushButton(ProgramForm)
        self.Button_4_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_4_Inside.setFont(font)
        self.Button_4_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_4_Inside.setObjectName("Button_4_Inside")
        self.gridLayout_10.addWidget(self.Button_4_Inside, 0, 1, 1, 1)
        self.Button_3_Inside = QtWidgets.QPushButton(ProgramForm)
        self.Button_3_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_3_Inside.setFont(font)
        self.Button_3_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_3_Inside.setObjectName("Button_3_Inside")
        self.gridLayout_10.addWidget(self.Button_3_Inside, 1, 0, 1, 1)
        self.Button_5_Inside = QtWidgets.QPushButton(ProgramForm)
        self.Button_5_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_5_Inside.setFont(font)
        self.Button_5_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_5_Inside.setObjectName("Button_5_Inside")
        self.gridLayout_10.addWidget(self.Button_5_Inside, 0, 0, 1, 1)
        self.Button_1_Inside = QtWidgets.QPushButton(ProgramForm)
        self.Button_1_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Button_1_Inside.setFont(font)
        self.Button_1_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Button_1_Inside.setObjectName("Button_1_Inside")
        self.gridLayout_10.addWidget(self.Button_1_Inside, 2, 1, 1, 1)
        self.Button_Emergency_Inside = QtWidgets.QToolButton(ProgramForm)
        self.Button_Emergency_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Emergency_Inside.setFont(font)
        self.Button_Emergency_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Resources/ISO_7010_F006_2-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Emergency_Inside.setIcon(icon7)
        self.Button_Emergency_Inside.setIconSize(QtCore.QSize(40, 40))
        self.Button_Emergency_Inside.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Button_Emergency_Inside.setObjectName("Button_Emergency_Inside")
        self.gridLayout_10.addWidget(self.Button_Emergency_Inside, 6, 1, 1, 1)
        self.Button_Open_Door_Inside = QtWidgets.QToolButton(ProgramForm)
        self.Button_Open_Door_Inside.setMinimumSize(QtCore.QSize(96, 66))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_Open_Door_Inside.setFont(font)
        self.Button_Open_Door_Inside.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(170, 148, 141, 255), stop:1 rgba(255, 255, 255, 255));")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Resources/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Open_Door_Inside.setIcon(icon8)
        self.Button_Open_Door_Inside.setIconSize(QtCore.QSize(40, 40))
        self.Button_Open_Door_Inside.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.Button_Open_Door_Inside.setObjectName("Button_Open_Door_Inside")
        self.gridLayout_10.addWidget(self.Button_Open_Door_Inside, 5, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_10, 1, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 0, 3, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button_S1 = QtWidgets.QPushButton(ProgramForm)
        self.Button_S1.setObjectName("Button_S1")
        self.gridLayout_2.addWidget(self.Button_S1, 2, 0, 1, 1)
        self.Button_S5 = QtWidgets.QPushButton(ProgramForm)
        self.Button_S5.setObjectName("Button_S5")
        self.gridLayout_2.addWidget(self.Button_S5, 4, 0, 1, 1)
        self.Button_S3 = QtWidgets.QPushButton(ProgramForm)
        self.Button_S3.setObjectName("Button_S3")
        self.gridLayout_2.addWidget(self.Button_S3, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.Button_S4 = QtWidgets.QPushButton(ProgramForm)
        self.Button_S4.setObjectName("Button_S4")
        self.gridLayout_2.addWidget(self.Button_S4, 2, 1, 1, 1)
        self.Button_S2 = QtWidgets.QPushButton(ProgramForm)
        self.Button_S2.setObjectName("Button_S2")
        self.gridLayout_2.addWidget(self.Button_S2, 5, 0, 1, 1)
        self.lineEdit_Align = QtWidgets.QLineEdit(ProgramForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Align.sizePolicy().hasHeightForWidth())
        self.lineEdit_Align.setSizePolicy(sizePolicy)
        self.lineEdit_Align.setMinimumSize(QtCore.QSize(225, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_Align.setFont(font)
        self.lineEdit_Align.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEdit_Align.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_Align.setText("")
        self.lineEdit_Align.setObjectName("lineEdit_Align")
        self.gridLayout_2.addWidget(self.lineEdit_Align, 3, 1, 1, 1)
        self.lineEdit__speed = QtWidgets.QLineEdit(ProgramForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit__speed.sizePolicy().hasHeightForWidth())
        self.lineEdit__speed.setSizePolicy(sizePolicy)
        self.lineEdit__speed.setMinimumSize(QtCore.QSize(225, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit__speed.setFont(font)
        self.lineEdit__speed.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEdit__speed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit__speed.setText("")
        self.lineEdit__speed.setObjectName("lineEdit__speed")
        self.gridLayout_2.addWidget(self.lineEdit__speed, 4, 1, 1, 1)
        self.lineEdit_wight = QtWidgets.QLineEdit(ProgramForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_wight.sizePolicy().hasHeightForWidth())
        self.lineEdit_wight.setSizePolicy(sizePolicy)
        self.lineEdit_wight.setMinimumSize(QtCore.QSize(225, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_wight.setFont(font)
        self.lineEdit_wight.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEdit_wight.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_wight.setText("")
        self.lineEdit_wight.setObjectName("lineEdit_wight")
        self.gridLayout_2.addWidget(self.lineEdit_wight, 5, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_20, 2, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(ProgramForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("qlineargradient (spread:pad, x1:0.0738636, y1:0.057, x2:1, y2:0, stop:0.335227 rgba(0, 0, 0, 255), stop:0.806818 rgba(115, 166, 255, 255))")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 81, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Resources/on1 (2).png"))
        self.label_6.setObjectName("label_6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(60, 20, 71, 101))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Resources/off2.png"))
        self.label_16.setObjectName("label_16")
        self.label_16.raise_()
        self.label_6.raise_()
        self.gridLayout.addWidget(self.groupBox_4, 2, 4, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line = QtWidgets.QFrame(ProgramForm)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(ProgramForm)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(ProgramForm)
        self.frame.setMinimumSize(QtCore.QSize(500, 800))
        self.frame.setStyleSheet("qlineargradient (spread:pad, x1:0.0738636, y1:0.057, x2:1, y2:0, stop:0.335227 rgba(0, 0, 0, 255), stop:0.806818 rgba(115, 166, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 0, 361, 781))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Resources/all elevator 5 floors v_2 L2.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(30, 10, 431, 751))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Resources/all elevator 5 floors v_2 L4.png"))
        self.label_10.setObjectName("label_10")
        self.Inside_Elvetor_Car = QtWidgets.QLabel(self.frame)
        self.Inside_Elvetor_Car.setGeometry(QtCore.QRect(30, -69, 481, 871))
        self.Inside_Elvetor_Car.setText("")
        self.Inside_Elvetor_Car.setPixmap(QtGui.QPixmap("Resources/all elevator 5 floors v_2 L3.png"))
        self.Inside_Elvetor_Car.setObjectName("Inside_Elvetor_Car")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(360, 40, 121, 681))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 620, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 350, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 490, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.open_door_5 = QtWidgets.QLabel(self.frame)
        self.open_door_5.setGeometry(QtCore.QRect(203, 40, 173, 161))
        self.open_door_5.setText("")
        self.open_door_5.setTextFormat(QtCore.Qt.RichText)
        self.open_door_5.setPixmap(QtGui.QPixmap("Resources/elevator car from close to open.gif"))
        self.open_door_5.setScaledContents(True)
        self.open_door_5.setWordWrap(False)
        self.open_door_5.setOpenExternalLinks(False)
        self.open_door_5.setObjectName("open_door_5")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 510, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.open_door_4 = QtWidgets.QLabel(self.frame)
        self.open_door_4.setGeometry(QtCore.QRect(203, 178, 173, 161))
        self.open_door_4.setText("")
        self.open_door_4.setTextFormat(QtCore.Qt.RichText)
        self.open_door_4.setPixmap(QtGui.QPixmap("Resources/elevator car from close to open.gif"))
        self.open_door_4.setScaledContents(True)
        self.open_door_4.setWordWrap(False)
        self.open_door_4.setOpenExternalLinks(False)
        self.open_door_4.setObjectName("open_door_4")
        self.open_door_3 = QtWidgets.QLabel(self.frame)
        self.open_door_3.setGeometry(QtCore.QRect(203, 315, 173, 161))
        self.open_door_3.setText("")
        self.open_door_3.setTextFormat(QtCore.Qt.RichText)
        self.open_door_3.setPixmap(QtGui.QPixmap("Resources/elevator car from close to open.gif"))
        self.open_door_3.setScaledContents(True)
        self.open_door_3.setWordWrap(False)
        self.open_door_3.setOpenExternalLinks(False)
        self.open_door_3.setObjectName("open_door_3")
        self.open_door_2 = QtWidgets.QLabel(self.frame)
        self.open_door_2.setGeometry(QtCore.QRect(203, 450, 173, 161))
        self.open_door_2.setText("")
        self.open_door_2.setTextFormat(QtCore.Qt.RichText)
        self.open_door_2.setPixmap(QtGui.QPixmap("Resources/elevator car from close to open.gif"))
        self.open_door_2.setScaledContents(True)
        self.open_door_2.setWordWrap(False)
        self.open_door_2.setOpenExternalLinks(False)
        self.open_door_2.setObjectName("open_door_2")
        self.open_door_1 = QtWidgets.QLabel(self.frame)
        self.open_door_1.setGeometry(QtCore.QRect(203, 588, 173, 161))
        self.open_door_1.setText("")
        self.open_door_1.setTextFormat(QtCore.Qt.RichText)
        self.open_door_1.setPixmap(QtGui.QPixmap("Resources/elevator car from close to open.gif"))
        self.open_door_1.setScaledContents(True)
        self.open_door_1.setWordWrap(False)
        self.open_door_1.setOpenExternalLinks(False)
        self.open_door_1.setObjectName("open_door_1")
        self.close_door_1 = QtWidgets.QLabel(self.frame)
        self.close_door_1.setGeometry(QtCore.QRect(203, 588, 173, 161))
        self.close_door_1.setText("")
        self.close_door_1.setTextFormat(QtCore.Qt.RichText)
        self.close_door_1.setPixmap(QtGui.QPixmap("Resources/elevator car from open to close.gif"))
        self.close_door_1.setScaledContents(True)
        self.close_door_1.setWordWrap(False)
        self.close_door_1.setOpenExternalLinks(False)
        self.close_door_1.setObjectName("close_door_1")
        self.close_door_5 = QtWidgets.QLabel(self.frame)
        self.close_door_5.setGeometry(QtCore.QRect(203, 40, 173, 161))
        self.close_door_5.setText("")
        self.close_door_5.setTextFormat(QtCore.Qt.RichText)
        self.close_door_5.setPixmap(QtGui.QPixmap("Resources/elevator car from open to close.gif"))
        self.close_door_5.setScaledContents(True)
        self.close_door_5.setWordWrap(False)
        self.close_door_5.setOpenExternalLinks(False)
        self.close_door_5.setObjectName("close_door_5")
        self.close_door_3 = QtWidgets.QLabel(self.frame)
        self.close_door_3.setGeometry(QtCore.QRect(203, 315, 173, 161))
        self.close_door_3.setText("")
        self.close_door_3.setTextFormat(QtCore.Qt.RichText)
        self.close_door_3.setPixmap(QtGui.QPixmap("Resources/elevator car from open to close.gif"))
        self.close_door_3.setScaledContents(True)
        self.close_door_3.setWordWrap(False)
        self.close_door_3.setOpenExternalLinks(False)
        self.close_door_3.setObjectName("close_door_3")
        self.close_door_4 = QtWidgets.QLabel(self.frame)
        self.close_door_4.setGeometry(QtCore.QRect(203, 178, 173, 161))
        self.close_door_4.setText("")
        self.close_door_4.setTextFormat(QtCore.Qt.RichText)
        self.close_door_4.setPixmap(QtGui.QPixmap("Resources/elevator car from open to close.gif"))
        self.close_door_4.setScaledContents(True)
        self.close_door_4.setWordWrap(False)
        self.close_door_4.setOpenExternalLinks(False)
        self.close_door_4.setObjectName("close_door_4")
        self.close_door_2 = QtWidgets.QLabel(self.frame)
        self.close_door_2.setGeometry(QtCore.QRect(203, 450, 173, 161))
        self.close_door_2.setText("")
        self.close_door_2.setTextFormat(QtCore.Qt.RichText)
        self.close_door_2.setPixmap(QtGui.QPixmap("Resources/elevator car from open to close.gif"))
        self.close_door_2.setScaledContents(True)
        self.close_door_2.setWordWrap(False)
        self.close_door_2.setOpenExternalLinks(False)
        self.close_door_2.setObjectName("close_door_2")
        self.label_10.raise_()
        self.Inside_Elvetor_Car.raise_()
        self.label_9.raise_()
        self.groupBox.raise_()
        self.open_door_5.raise_()
        self.label_7.raise_()
        self.open_door_4.raise_()
        self.open_door_3.raise_()
        self.open_door_2.raise_()
        self.open_door_1.raise_()
        self.close_door_1.raise_()
        self.close_door_5.raise_()
        self.close_door_3.raise_()
        self.close_door_4.raise_()
        self.close_door_2.raise_()
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 2, 3, 1)
        self.retranslateUi(ProgramForm)
        self.hide_gif()


        ################################# all the clicked.connect: #################################




                            ##All the Key_Floor##
        self.Button_Key_Floor1.clicked.connect(lambda: self.set_user("operator", self.Button_Sys_Onoff_Floor_1))
        self.Button_Key_Floor2.clicked.connect(lambda: self.set_user("operator", self.Button_Sys_Onoff_Floor_2))
        self.Button_Key_Floor3.clicked.connect(lambda: self.set_user("operator", self.Button_Sys_Onoff_Floor_3))
        self.Button_Key_Floor4.clicked.connect(lambda: self.set_user("operator", self.Button_Sys_Onoff_Floor_4))
        self.Button_Key_Floor5.clicked.connect(lambda: self.set_user("operator", self.Button_Sys_Onoff_Floor_5))
        self.Button_Key_Inside.clicked.connect(lambda: self.set_user("operator", self.Button_Sys_Onoff_Inside))

                          ## All the Sys_Onoff ##
        self.Button_Sys_Onoff_Inside.clicked.connect(lambda: self.turn_on_off())
        self.Button_Sys_Onoff_Floor_1.clicked.connect(lambda: self.turn_on_off())
        self.Button_Sys_Onoff_Floor_2.clicked.connect(lambda: self.turn_on_off())
        self.Button_Sys_Onoff_Floor_3.clicked.connect(lambda: self.turn_on_off())
        self.Button_Sys_Onoff_Floor_4.clicked.connect(lambda: self.turn_on_off())
        self.Button_Sys_Onoff_Floor_5.clicked.connect(lambda: self.turn_on_off())

                        ##All the Up and Down buttons ##
        self.Button_Up_Floor_1.clicked.connect(lambda: self.floor_call(1))
        self.Button_Up_Floor_2.clicked.connect(lambda: self.floor_call(2))
        self.Button_Up_Floor_3.clicked.connect(lambda: self.floor_call(3))
        self.Button_Up_Floor_4.clicked.connect(lambda: self.floor_call(4))
        self.Button_Down_Floor_2.clicked.connect(lambda: self.floor_call(2))
        self.Button_Down_Floor_3.clicked.connect(lambda: self.floor_call(3))
        self.Button_Down_Floor_4.clicked.connect(lambda: self.floor_call(4))
        self.Button_Down_Floor_5.clicked.connect(lambda: self.floor_call(5))


                         ## All the inside number buttons ##
        self.Button_1_Inside.clicked.connect(lambda: self.floor_call(1))
        self.Button_2_Inside.clicked.connect(lambda: self.floor_call(2))
        self.Button_3_Inside.clicked.connect(lambda: self.floor_call(3))
        self.Button_4_Inside.clicked.connect(lambda: self.floor_call(4))
        self.Button_5_Inside.clicked.connect(lambda: self.floor_call(5))


                        ## All the other Inside buttons ##
        # need the emergency function to work
        self.Button_Open_Door_Inside.clicked.connect(lambda: self.system.open_door())
        self.Button_Close_Door_Inside.clicked.connect(lambda: self.system.close_door())
        self.Button_Emergency_Inside.clicked.connect(lambda: self.system.in_emergency())
        self.Button_Stop_Inside.clicked.connect(lambda: self.system.get_car().stop())

        # All the sensors: ##
        self.Button_S1.clicked.connect(lambda: self.smoke_button())
        self.Button_S2.clicked.connect(lambda: self.weight_button())
        self.Button_S3.clicked.connect(lambda: self.alignment_button())
        self.Button_S4.clicked.connect(lambda: self.laser_sensor_button())
        self.Button_S5.clicked.connect(lambda: self.Speed_Sensor_button())


        ################################# end of clicked.connect #################################

        ################################# .gif #################################



# open


# close


        ################################# end #################################

        QtCore.QMetaObject.connectSlotsByName(ProgramForm)
        ProgramForm.setTabOrder(self.Button_1_Inside, self.Button_2_Inside)
        ProgramForm.setTabOrder(self.Button_2_Inside, self.Button_3_Inside)
        ProgramForm.setTabOrder(self.Button_3_Inside, self.Button_4_Inside)
        ProgramForm.setTabOrder(self.Button_4_Inside, self.Button_5_Inside)
        ProgramForm.setTabOrder(self.Button_5_Inside, self.Button_Stop_Inside)
        ProgramForm.setTabOrder(self.Button_Stop_Inside, self.Button_Key_Inside)
        ProgramForm.setTabOrder(self.Button_Key_Inside, self.Button_Sys_Onoff_Inside)
        ProgramForm.setTabOrder(self.Button_Sys_Onoff_Inside, self.Button_Down_Floor_3)
        ProgramForm.setTabOrder(self.Button_Down_Floor_3, self.Button_Up_Floor_3)
        ProgramForm.setTabOrder(self.Button_Up_Floor_3, self.Button_Sys_Onoff_Floor_3)
        ProgramForm.setTabOrder(self.Button_Sys_Onoff_Floor_3, self.Button_Key_Floor3)
        ProgramForm.setTabOrder(self.Button_Key_Floor3, self.Button_Down_Floor_2)
        ProgramForm.setTabOrder(self.Button_Down_Floor_2, self.Display_Floor4)
        ProgramForm.setTabOrder(self.Display_Floor4, self.Button_Key_Floor2)
        ProgramForm.setTabOrder(self.Button_Key_Floor2, self.Button_Sys_Onoff_Floor_1)
        ProgramForm.setTabOrder(self.Button_Sys_Onoff_Floor_1, self.Display_Floor5)
        ProgramForm.setTabOrder(self.Display_Floor5, self.Button_Sys_Onoff_Floor_5)
        ProgramForm.setTabOrder(self.Button_Sys_Onoff_Floor_5, self.Button_Down_Floor_5)
        ProgramForm.setTabOrder(self.Button_Down_Floor_5, self.Display_Floor3)
        ProgramForm.setTabOrder(self.Display_Floor3, self.Button_Up_Floor_1)
        ProgramForm.setTabOrder(self.Button_Up_Floor_1, self.Display_Floor2)
        ProgramForm.setTabOrder(self.Display_Floor2, self.Display_Floor1)
        ProgramForm.setTabOrder(self.Display_Floor1, self.Button_Key_Floor1)
        ProgramForm.setTabOrder(self.Button_Key_Floor1, self.Button_Key_Floor4)
        ProgramForm.setTabOrder(self.Button_Key_Floor4, self.Button_Down_Floor_4)
        ProgramForm.setTabOrder(self.Button_Down_Floor_4, self.Button_Up_Floor_4)
        ProgramForm.setTabOrder(self.Button_Up_Floor_4, self.Button_Key_Floor5)
        ProgramForm.setTabOrder(self.Button_Key_Floor5, self.Button_Sys_Onoff_Floor_4)
        ProgramForm.setTabOrder(self.Button_Sys_Onoff_Floor_4, self.Button_Sys_Onoff_Floor_2)
        ProgramForm.setTabOrder(self.Button_Sys_Onoff_Floor_2, self.Button_Up_Floor_2)

        ################################# sensors Check #################################
    def smoke_button(self):
        if not self.system.get_sensor_controller().get_smoke().get_measure():
            smoke = self.system.get_sensor_controller().get_smoke()
            self.system.get_sensor_controller().set_sensor_measure(smoke, True)
            self.Button_S1.setText("Stop testing smoke")
            self.lineEdit_6.setText("Activated")
        else:
            smoke = self.system.get_sensor_controller().get_smoke()
            self.system.get_sensor_controller().set_sensor_measure(smoke, False)
            self.Button_S1.setText("There is smoke")
            self.lineEdit_6.setText("Not Active")
            self.reset()

    def weight_button(self):
        if self.system.get_sensor_controller().get_weight().get_measure() <= 1600.0:
            weight = self.system.get_sensor_controller().get_weight()
            self.system.get_sensor_controller().set_sensor_measure(weight, float(self.lineEdit_wight.text()))
            self.Button_S2.setText("Stop testing Weight sensor")
            self.lineEdit_6.setText("Activated")
        else:
            self.Button_S2.setText("The weight = ")
            self.lineEdit_6.setText("Not Active")
            self.reset()


            # need some changes

    def alignment_button(self):
        if self.system.get_sensor_controller().get_pos().get_measure() <= 0.5:
            position = self.system.get_sensor_controller().get_pos()
            self.system.get_sensor_controller().set_sensor_measure(position, 3000)
            self.Button_S3.setText("Stop alignment testing")
            self.lineEdit_6.setText("Activated")
        else:
            self.Button_S3.setText("The Car is Not Aligned with the Floor by =")
            self.lineEdit_6.setText("Not Active")
            self.reset()



            # need some changes

    def laser_sensor_button(self):
        if not self.system.get_sensor_controller().get_door().get_measure():
            door = self.system.get_sensor_controller().get_door()
            self.system.get_sensor_controller().set_sensor_measure(door, True)
            self.Button_S4.setText("Stop testing laser sensor ")

        else:
            self.Button_S4.setText("There Is an Object between the Doors ")
            self.reset()


    def Speed_Sensor_button(self):
        if self.system.get_sensor_controller().get_weight().get_measure() <= 1600.0:
            weight = self.system.get_sensor_controller().get_weight()
            self.system.get_sensor_controller().set_sensor_measure(weight, 3000)
            self.Button_S5.setText("Stop testing Speed Sensor")
            self.lineEdit_6.setText("Activated")
        else:
            self.Button_S5.setText("The speed =")
            self.lineEdit_6.setText("Not Active")
            self.reset()

                ################################# End of sensors Check #################################

        labelHide = True

    def turn_on_off(self):
        if self.system.is_on():
            self.label_6.hide()
            self.labelHide = False
            self.system.turn_off()
        else:
            self.label_6.show()
            self.labelHide = True
            self.system.turn_on()

    def Update_Display(self):
        self.Diplay_Inside.display(self.system.get_floor())
        self.Display_Floor1.setText(str(self.system.get_floor()))
        self.Display_Floor2.setText(str(self.system.get_floor()))
        self.Display_Floor3.setText(str(self.system.get_floor()))
        self.Display_Floor4.setText(str(self.system.get_floor()))
        self.Display_Floor5.setText(str(self.system.get_floor()))

    def hide_gif(self):
        self.open_door_1.hide()
        self.open_door_2.hide()
        self.open_door_3.hide()
        self.open_door_4.hide()
        self.open_door_5.hide()
        self.close_door_1.hide()
        self.close_door_2.hide()
        self.close_door_3.hide()
        self.close_door_4.hide()
        self.close_door_5.hide()


    def reset(self):
        self.system.reset()

    def open_door(self):
        if self.system.get_floor() == 5:
            self.label_8.setText("Open")
            self.open_door_5.show()

            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()

            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            open_door_5_gif = QtGui.QMovie("Resources/elevator car from close to open.gif")
            self.open_door_5.setMovie(open_door_5_gif)
            open_door_5_gif.start()

        elif self.system.get_floor() == 4:
            self.label_12.setText("Open")
            self.open_door_4.show()
            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()

            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            open_door_4_gif = QtGui.QMovie("Resources/elevator car from close to open.gif")
            self.open_door_4.setMovie(open_door_4_gif)
            open_door_4_gif.start()

        elif self.system.get_floor() == 3:
            self.label_13.setText("Open")
            self.open_door_3.show()
            self.open_door_1.hide()
            self.open_door_2.hide()

            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            open_door_3_gif = QtGui.QMovie("Resources/elevator car from close to open.gif")
            self.open_door_3.setMovie(open_door_3_gif)
            open_door_3_gif.start()

        elif self.system.get_floor() == 2:
            self.label_14.setText("Open")
            self.open_door_2.show()
            self.open_door_1.hide()

            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            open_door_2_gif = QtGui.QMovie("Resources/elevator car from close to open.gif")
            self.open_door_2.setMovie(open_door_2_gif)
            open_door_2_gif.start()

        elif self.system.get_floor() == 1:
            self.label_15.setText("Open")
            self.open_door_1.show()

            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            open_door_1_gif = QtGui.QMovie("Resources/elevator car from close to open.gif")
            self.open_door_1.setMovie(open_door_1_gif)
            open_door_1_gif.start()



    def close_door(self):


        if self.system.get_floor() == 5:
            self.label_8.setText("Close")
            self.close_door_5.show()
            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()

            close_door_5_gif = QtGui.QMovie("Resources/elevator car from open to close.gif")
            self.close_door_5.setMovie(close_door_5_gif)
            close_door_5_gif.start()

        elif self.system.get_floor() == 4:
            self.label_12.setText("Close")
            self.close_door_4.show()
            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()
            self.close_door_3.hide()

            self.close_door_5.hide()
            close_door_4_gif = QtGui.QMovie("Resources/elevator car from open to close.gif")
            self.close_door_4.setMovie(close_door_4_gif)
            close_door_4_gif.start()

        elif self.system.get_floor() == 3:
            self.label_13.setText("Close")
            self.close_door_3.show()
            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()
            self.close_door_2.hide()

            self.close_door_4.hide()
            self.close_door_5.hide()
            close_door_3_gif = QtGui.QMovie("Resources/elevator car from open to close.gif")
            self.close_door_3.setMovie(close_door_3_gif)
            close_door_3_gif.start()

        elif self.system.get_floor() == 2:
            self.label_14.setText("Close")

            self.close_door_2.show()
            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()
            self.close_door_1.hide()

            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            close_door_2_gif = QtGui.QMovie("Resources/elevator car from open to close.gif")
            self.close_door_2.setMovie(close_door_2_gif)
            close_door_2_gif.start()

        elif self.system.get_floor() == 1:
            self.label_15.setText("Close")
            self.close_door_1.show()
            self.open_door_1.hide()
            self.open_door_2.hide()
            self.open_door_3.hide()
            self.open_door_4.hide()
            self.open_door_5.hide()

            self.close_door_2.hide()
            self.close_door_3.hide()
            self.close_door_4.hide()
            self.close_door_5.hide()
            close_door_1_gif = QtGui.QMovie("Resources/elevator car from open to close.gif")
            self.close_door_1.setMovie(close_door_1_gif)
            close_door_1_gif.start()













    def floor_call (self, floor):
        self.system.add_request("move", floor, self.user)

    def move(self, y):
        new_pos = self.Inside_Elvetor_Car.y() + y
        self.Inside_Elvetor_Car.move(30, new_pos)


    def set_user(self, user, button):
        if self.user is "operator":
            button.setEnabled(False)
            self.user = "passenger"
        else:
            button.setEnabled(True)
            self.user = "operator"

    def get_sys(self):
        return self.system

    def test_emergency(self):
        speed = self.system.get_sensor_controller().get_speed()
        self.system.get_sensor_controller().set_sensor_measure(speed, 90)

    ################################# End #################################
    def retranslateUi(self, ProgramForm):
        _translate = QtCore.QCoreApplication.translate
        ProgramForm.setWindowTitle(_translate("ProgramForm", "Group 4 Elevator project"))
        self.label_24.setText(_translate("ProgramForm", "Group 4 Elevator Project"))
        self.label_25.setText(_translate("ProgramForm", "Outside the Elevator "))
        self.Button_Down_Floor_5.setText(_translate("ProgramForm", "down"))
        self.label_20.setText(_translate("ProgramForm", "Display"))
        self.Display_Floor5.setText(_translate("ProgramForm", "1"))
        self.Button_Key_Floor5.setText(_translate("ProgramForm", "operator key"))
        self.Button_Sys_Onoff_Floor_5.setText(_translate("ProgramForm", "system on/off"))
        self.label.setText(_translate("ProgramForm", "floor 5"))
        self.Button_Up_Floor_3.setText(_translate("ProgramForm", "up"))
        self.Button_Down_Floor_3.setText(_translate("ProgramForm", "down"))
        self.Button_Sys_Onoff_Floor_3.setText(_translate("ProgramForm", "system on/off"))
        self.Button_Key_Floor3.setText(_translate("ProgramForm", "operator key"))
        self.label_18.setText(_translate("ProgramForm", "Display"))
        self.Display_Floor3.setText(_translate("ProgramForm", "1"))
        self.label_3.setText(_translate("ProgramForm", "floor 3"))
        self.Button_Up_Floor_2.setText(_translate("ProgramForm", "up"))
        self.Button_Key_Floor2.setText(_translate("ProgramForm", "operator key"))
        self.Button_Sys_Onoff_Floor_2.setText(_translate("ProgramForm", "system on/off"))
        self.Button_Down_Floor_2.setText(_translate("ProgramForm", "down"))
        self.label_21.setText(_translate("ProgramForm", "Display"))
        self.Display_Floor2.setText(_translate("ProgramForm", "1"))
        self.label_4.setText(_translate("ProgramForm", "floor 2"))
        self.Button_Down_Floor_4.setText(_translate("ProgramForm", "down"))
        self.label_19.setText(_translate("ProgramForm", "Display"))
        self.Display_Floor4.setText(_translate("ProgramForm", "1"))
        self.Button_Up_Floor_4.setText(_translate("ProgramForm", "up"))
        self.Button_Key_Floor4.setText(_translate("ProgramForm", "operator key"))
        self.Button_Sys_Onoff_Floor_4.setText(_translate("ProgramForm", "system on/off"))
        self.label_2.setText(_translate("ProgramForm", "floor 4"))
        self.Button_Sys_Onoff_Floor_1.setText(_translate("ProgramForm", "system on/off"))
        self.Button_Up_Floor_1.setText(_translate("ProgramForm", "up"))
        self.Button_Key_Floor1.setText(_translate("ProgramForm", "operator key"))
        self.label_22.setText(_translate("ProgramForm", "Display"))
        self.Display_Floor1.setText(_translate("ProgramForm", "1"))
        self.label_5.setText(_translate("ProgramForm", "floor 1"))
        self.lineEdit_6.setText(_translate("ProgramForm", "not active"))
        self.label_17.setText(_translate("ProgramForm", "Display"))
        self.label_11.setText(_translate("ProgramForm", "Inside the Elevator "))
        self.Button_Close_Door_Inside.setText(_translate("ProgramForm", "Close"))
        self.Button_Stop_Inside.setText(_translate("ProgramForm", "STOP"))
        self.Button_2_Inside.setText(_translate("ProgramForm", "2"))
        self.Button_Sys_Onoff_Inside.setText(_translate("ProgramForm", "system on/off"))
        self.Button_Key_Inside.setText(_translate("ProgramForm", "operator key"))
        self.Button_4_Inside.setText(_translate("ProgramForm", "4"))
        self.Button_3_Inside.setText(_translate("ProgramForm", "3"))
        self.Button_5_Inside.setText(_translate("ProgramForm", "5"))
        self.Button_1_Inside.setText(_translate("ProgramForm", "1"))
        self.Button_Emergency_Inside.setText(_translate("ProgramForm", "Emergency Call"))
        self.Button_Open_Door_Inside.setText(_translate("ProgramForm", "Open"))
        self.Button_S1.setText(_translate("ProgramForm", "There is smoke"))
        self.Button_S5.setText(_translate("ProgramForm", "The speed ="))
        self.Button_S3.setText(_translate("ProgramForm", "The Car is Not Aligned with the Floor by ="))
        self.label_28.setText(_translate("ProgramForm", "Scenarios"))
        self.Button_S4.setText(_translate("ProgramForm", "There Is an Object between the Doors"))
        self.Button_S2.setText(_translate("ProgramForm", "The weight = "))
        self.groupBox_4.setTitle(_translate("ProgramForm", "system"))
        self.groupBox.setTitle(_translate("ProgramForm", "door situation"))
        self.label_15.setText(_translate("ProgramForm", "Close"))
        self.label_13.setText(_translate("ProgramForm", "Close"))
        self.label_14.setText(_translate("ProgramForm", "Close"))
        self.label_12.setText(_translate("ProgramForm", "Close"))
        self.label_8.setText(_translate("ProgramForm", "Close"))


